name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
author: MegaNarwhal_
depend: [Vault]
description: Shop GUIs.
commands:
  shop:
    description: Open the shop GUI.
    usage: /<command>
  shopui:
    description: Manage ShopUI shops.
    usage: /<command>
permissions:
  shopui.command.shop:
    default: true
  shopui.command.manage:
    default: op